Remove mention of pip in favor of conda
As of this commit, this package is installable using `conda` via
binstar.org. However, there is still one issue. This package works if
installed into an environment with anaconda, but not in a plain python
environment, even if the anaconda metapackage is installed afterwards.

What works
==========

```
$ conda create -yp env anaconda
$ source activate ./env
$ conda install -c jrsmith3/channels/test physicalproperty
```

At this point, `physicalproperty` can be imported into an ipython
environment. Additionally, executing the tests from the
`physicalproperty` package via nose works as well.

What doesn't work
=================

```
$ conda create -yp env python
$ source activate ./env
$ conda install -c jrsmith3/channels/test physicalproperty
```

At this point, the `physicalproperty` package cannot be `import`ed into
an ipython environment and the tests from the `physicalproperty` package
will throw `ImportError` exceptions.

```
ERROR: Failure: ImportError (No module named physicalproperty)
```

Executing the following command does not help.

```
$ conda install anaconda
```

Despite this bug, I am going to declare that these commits close #9
since there is a way to install this package using `conda`, and this new
bug seems related but distinct from the original issue.

Closes #9.